### ISSUE TITLE
Not displaying polygons and points

### ISSUE THREAD

**Issue by ChandlerBuck** [IvanSanchez/Leaflet.VectorGrid#11]
I am using Leaflet 1.00-rc2 and my map will only show lines when loading in the protobuf files. There are polygons and points in the protobuf files.

**Comment by ChandlerBuck** [comment]
Does this plugin not allow for polygons and points?

**Comment by IvanSanchez** [comment]
Please read the README.md file before asking, as it says:

> At this time, only polylines and polygons can be styled. There is no support (yet) for symbolizing points.
