### ISSUE TITLE
Building bundled file for Leaflet 1.0

### ISSUE THREAD

**Issue by hrishiballal** [IvanSanchez/Leaflet.VectorGrid#17]
I am trying to use this library with Leaflet 1.0.1 and a couple of things:

- What is the best way to build a new bundled file? I am specifically working on GeoJSON data.
- I tried to use a old bundled file but it does not work with the new Leaflet release, I think it is incompatible with the new release, am I correct?

Thank you again for your help with his and a great library.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet.VectorGrid useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using this, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by hrishiballal** [comment]
Well there are two bugs really then: 
- There is no bundled file provided in the repo (it is mentioned in the documentation to use the bundled file) 
- If I use the old bundled file with leaflet 1.0.1 it does not work. 

I will open these bugs. Thanks again!
