### ISSUE TITLE
Best way to iterate over each feature?

### ISSUE THREAD

**Issue by brendanvinson** [IvanSanchez/Leaflet.VectorGrid#4]
I'm using this to implement protobuf tiles, but I was wondering if was possible to iterate over features similar to http://leafletjs.com/reference-1.0.0.html#geojson-oneachfeature?

In this specific case I'm trying to attach an event to each feature, but I'm having problems even getting `L.GridLayer()` (which you extend) to take an `on()` event.

**Comment by IvanSanchez** [comment]
> Is it possible to [...]?

No.

This plugin is a `GridLayer`, not a `LayerGroup`. And the logic doesn't need to keep copies of the features anywhere, but call the slicer or the network when a tile is needed.

There is (arguably) a use case for interactivity of `VectorGrid`s. It would involve delegating UI events to the appropriate tile renderer (**not** attaching individual events - be efficient!), and I haven't tackled that problem yet (as my particular use case doesn't involve interactivity and have some other priorities).

**Comment by brendanvinson** [comment]
That being the case, is there a way to add a label to each displayed feature?

**Comment by IvanSanchez** [comment]
Not as of now.

The code does iterate through the features in the vector tiles, but just in order to send data to the SVG/canvas renderer. Anything beyond that will have to be coded.

**Comment by brendanvinson** [comment]
That's sort of what I suspected. I guess I'm back to using raster tiles for now.
