### ISSUE TITLE
Need idea on this implemtation of mouse click event

### ISSUE THREAD

**Issue by haoliangyu** [IvanSanchez/Leaflet.VectorGrid#5]
Here is my implementation of mouse click handler. To add the click event handler, one needs to specify the `options.onClick` when initializing `L.vectorGrid.protobuf` and it could be

* a handler function that will be applied to all layers

``` javascript
var options = {
    onClick: function(e) {
        // handler
    },
    ...
}
```

* an object that defines handlers for specific layers

``` javascript
var options = {
    onClick: {
        // layer name
        water: function(e) {
            // handler
        }
    },
    ...
}
```

The parameter `e` is a standard leaflet event object.

``` javascript
{
    type: 'click',
    target: feature // clicked VectorTileFeature
}
```

The following code is added at `Leaflet.VectorGrid.js` line 44 in order to add necessary information and mouse event handler to the feature:

``` javascript
feat.layerName = layerName;
feat.coords = coords;

var onClick = this.options.onClick;
if (typeof onClick === 'function') {
    feat.onClick = onClick;
} else if (typeof onClick === 'object') {
    if (typeof onClick[layerName] === 'function') {
        feat.onClick = onClick[layerName];
    }
}
```

The event handler is binded to the `path` element by decorating the `_initPath` function at `Leaflet.Render.SVG.Tile.js`:

``` javascript
_initPath: function(layer) {
    L.SVG.prototype._initPath.call(this, layer);

      var path = layer._path;

      if (typeof layer.onClick === 'function') {
        if (layer.type === 2) {
            path.setAttribute('pointer-events', 'stroke');
        } else if (layer.type === 3) {
            path.setAttribute('pointer-events', 'fill');
        } else if (layer.type === 1) {
            path.setAttribute('pointer-events', 'painted');
        }

        path.addEventListener('click', function(e) {
            layer.onClick({ type: 'click', target: layer });
        });
    }
}
```

The implemetation is at [here](https://github.com/haoliangyu/Leaflet.VectorGrid/tree/feature/mouseClick) and a demo is at [here](https://github.com/haoliangyu/Leaflet.VectorGrid/blob/feature/mouseClick/demo/demo-click.html).

This is slightly different from #3 as I didn't add `_onClick()` to `L.GridLayer` and decorate the `getEvents()`. It seems that doing so would add a global click event to the `map` object, which is unnecessary.

The problem is that it looks different from the default event binding style, which uses `on()` and `off()`.

@IvanSanchez How do you think?

**Comment by JowieXiang** [comment]
@haoliangyu  Any follow-ups?

**Comment by haoliangyu** [comment]
@JowieXiang Unfortunately I am no longer working with Leaflet and unable to provide any follow-up in terms of coding. After reviewing my original proposal, I think the implementation was problematic because it used different value types for the same option. If you are interested in forking this repo and adding a fix, I will be happy to help.
