### ISSUE TITLE
Any way to render .pbf vector tiles using tm2 styles ?

### ISSUE THREAD

**Issue by nouryf** [IvanSanchez/Leaflet.VectorGrid#6]
It would pretty handy if rendering 'protobuf vector tiles' in leaflet would display data using mapbox .tm2 styles ? Any plan to add such support in future ? 

for ex. Mapbox 'osm-bright: https://github.com/mapbox/mapbox-studio-osm-bright.tm2

Thanks

**Comment by IvanSanchez** [comment]
Nope. This is only for reading vector tiles and rendering them using Leaflet styling rules. Feel free to develop something that translate .tm2 styles and symbolizers into Leaflet style rules for `L.Path`s.
